/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";var t=Object.defineProperty;var m=Object.getOwnPropertyDescriptor;var c=Object.getOwnPropertyNames;var i=Object.prototype.hasOwnProperty;var f=(e,a)=>{for(var n in a)t(e,n,{get:a[n],enumerable:!0})},k=(e,a,n,l)=>{if(a&&typeof a=="object"||typeof a=="function")for(let o of c(a))!i.call(e,o)&&o!==n&&t(e,o,{get:()=>a[o],enumerable:!(l=m(a,o))||l.enumerable});return e};var p=e=>k(t({},"__esModule",{value:!0}),e);var r={};f(r,{default:()=>d});module.exports=p(r);var s=require("obsidian"),d=class extends s.Plugin{async onload(){this.addCommand({id:"smoke-test",name:"\u5192\u70DF\u6D4B\u8BD5\uFF1A\u786E\u8BA4\u63D2\u4EF6\u5DF2\u52A0\u8F7D",callback:()=>{new s.Notice("\u63D2\u4EF6\u5DF2\u5C31\u7EEA")}})}onunload(){}};
